import { getSupabaseAdmin } from "./supabase-server";

/**
 * Typed database helpers — use these instead of raw .insert() / .update()
 * until database.ts is auto-generated by the GitHub Action.
 * 
 * Once the GitHub Action runs and commits the real types, these helpers
 * can be replaced with direct calls and the casts removed.
 */

export async function dbInsert<T extends Record<string, unknown>>(
  table: string,
  values: T
) {
  return getSupabaseAdmin().from(table).insert(values as T);
}

export async function dbInsertMany<T extends Record<string, unknown>>(
  table: string,
  values: T[]
) {
  return getSupabaseAdmin().from(table).insert(values as T[]);
}

export async function dbUpdate<T extends Record<string, unknown>>(
  table: string,
  values: Partial<T>
) {
  return getSupabaseAdmin().from(table).update(values as Partial<T>);
}

export async function dbUpsert<T extends Record<string, unknown>>(
  table: string,
  values: T
) {
  return getSupabaseAdmin().from(table).upsert(values as T);
}
